export const styles = {
  pageContainer: "max-w-full mx-auto",
  sectionContainer: "mb-8 animate-fadeIn",
  
  h1: "text-4xl font-extrabold text-zinc-900 dark:text-zinc-50 mb-4 tracking-tight",
  h2: "text-xl font-bold mb-4 text-zinc-800 dark:text-zinc-200",
  textStandard: "text-zinc-600 dark:text-zinc-400",
  textLink: "text-blue-600 dark:text-blue-400 hover:underline",
  
  buttonIcon: "p-2 text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors",
  inputBase: "w-full bg-transparent text-sm text-zinc-800 dark:text-zinc-200 outline-none placeholder-zinc-500",
  inputContainer: "flex items-center bg-white dark:bg-[#121214] border border-zinc-300 dark:border-zinc-700 rounded-full px-4 py-1.5 shadow-sm focus-within:border-blue-500 focus-within:ring-0 transition-all",
  
  cardBase: "bg-zinc-100 dark:bg-zinc-900 rounded-xl p-6 border border-zinc-200 dark:border-zinc-800",
  gridListHeader: "grid grid-cols-[minmax(180px,1.2fr)_minmax(200px,3fr)_minmax(160px,1.1fr)_90px_90px_80px] gap-4 px-4",
  
  tagBase: "px-2 py-1 rounded text-xs font-bold",
  layoutRoot: "flex flex-col min-h-screen bg-zinc-100 dark:bg-[#111114] text-zinc-900 dark:text-zinc-100 transition-colors duration-200 font-sans",
  layoutContainer: "mx-[10%] lg:mx-[18%] py-8 flex-1",
  footer: "w-full py-6 text-center text-xs text-zinc-400 dark:text-zinc-600 bg-transparent",

  pageHeaderContainer: "mb-8 border-b border-zinc-200 dark:border-zinc-800 pb-6",
  codeSnippetContainer: "my-6 rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#18181b]",
  codeSnippetHeader: "px-4 py-2 bg-zinc-100 dark:bg-zinc-800/50 border-b border-zinc-200 dark:border-zinc-800 text-xs font-mono text-zinc-500 uppercase",
  codeSnippetBody: "p-4 overflow-x-auto",
  codeSnippetPre: "text-sm font-mono text-zinc-700 dark:text-zinc-300",
  contentSectionH2: "text-xl font-bold mb-4 text-zinc-800 dark:text-zinc-200 border-b border-zinc-200 dark:border-zinc-800 pb-2",
  contentSectionText: "text-zinc-600 dark:text-zinc-400 leading-relaxed space-y-4",

  /* Blog page / registry */
  animateFadeIn: "animate-fadeIn",
  blogRegistryPlaceholder: "italic text-zinc-500",
  blogRegistryMt4: "mt-4",

  /* Blog entry */
  blogEntryNotFound: "text-center py-20 text-zinc-500",
  blogEntryContainer: "max-w-3xl mx-auto py-8 animate-fadeIn",
  blogEntryMb8: "mb-8",
  blogEntryBackLink: "text-xs font-bold uppercase text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors mb-4 inline-flex items-center gap-1",
  blogEntryMetaRow: "flex items-center gap-3 text-sm text-zinc-500 dark:text-zinc-400 font-mono mb-6",
  blogEntryMetaInner: "flex gap-1",
  blogEntryCatBadge: "uppercase tracking-wider font-sans font-bold text-[10px] bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded",
  blogEntryExcerptExtras: "text-xl leading-relaxed font-light mb-8 italic border-l-4 border-zinc-200 dark:border-zinc-800 pl-4",
  blogEntryProse: "prose dark:prose-invert max-w-none text-zinc-700 dark:text-zinc-300",
  blogEntryPendingBox: "p-8 bg-zinc-50 dark:bg-zinc-900 rounded-lg text-center text-zinc-500",

  /* Blog list / page */
  blogPageRoot: "max-w-full",
  blogPageCategoriesRow: "flex gap-2 mb-10 overflow-x-auto pb-2 custom-scrollbar",
  blogPageCategoryBtn: "px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wide transition-all whitespace-nowrap",
  blogPageSpaceY: "space-y-12 animate-fadeIn",
  blogPagePostCard: "flex flex-col gap-2 group",
  blogPagePostTop: "flex items-center gap-3",
  blogPageDateText: "text-xs font-mono text-zinc-400 dark:text-zinc-500",
  blogPageTagRow: "flex gap-1",
  blogPageTagBadge: "text-[10px] font-bold uppercase tracking-wider text-zinc-400 border border-zinc-200 dark:border-zinc-800 px-1.5 py-0.5 rounded",
  blogPageLinkWrapper: "block w-fit",
  blogPageTitle: "text-2xl font-bold text-zinc-800 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors",
  blogPageExcerptExtras: "leading-relaxed max-w-3xl",
  blogPageReadMore: "mt-2 text-blue-600 dark:text-blue-400 text-sm font-medium flex items-center gap-1 hover:gap-2 transition-all w-fit",
  blogPageNoPosts: "text-center py-20 text-zinc-400 italic",

  /* Chess pages */
  chessPageRoot: "max-w-full",
  chessPageTextCenterLeft: "text-center md:text-left",
  chessPageGrid: "grid grid-cols-1 md:grid-cols-2 gap-8 mt-8",
  chessPageSpaceY: "space-y-4",
  chessPageItem: "flex justify-between items-center p-3 bg-white dark:bg-zinc-800/50 rounded-lg border border-zinc-200 dark:border-zinc-700/50",
  chessPageFlexCol: "flex flex-col",
  chessPagePlayerText: "font-bold text-sm text-zinc-700 dark:text-zinc-200",
  chessPageSmallText: "text-xs text-zinc-500",
  chessPageStatusWon: "text-sm font-mono text-green-600 dark:text-green-400",
  chessPageGrid2: "grid grid-cols-2 gap-4",
  chessPageStatBox1: "p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg text-center",
  chessPageStatBox2: "p-4 bg-violet-50 dark:bg-violet-900/20 rounded-lg text-center",
  chessPageStatValue1: "text-2xl font-bold text-blue-600 dark:text-blue-400",
  chessPageStatLabel1: "text-xs text-blue-800 dark:text-blue-300 uppercase tracking-wide font-bold mt-1",
  chessPageStatValue2: "text-2xl font-bold text-violet-600 dark:text-violet-400",

  /* Chess entry */
  chessEntryNotFound: "text-center py-20 text-zinc-500",
  chessEntryContainer: "max-w-3xl mx-auto py-8 animate-fadeIn",
  chessEntryMb8: "mb-8",
  chessEntryParaExtras: "text-lg mb-4",
  chessEntryTagsRow: "flex flex-wrap gap-4 text-sm text-zinc-500 dark:text-zinc-400",
  chessEntryPgnBox: "bg-zinc-50 dark:bg-zinc-900 rounded-lg p-6 border border-zinc-200 dark:border-zinc-800",
  chessEntryPre: "font-mono text-sm text-zinc-700 dark:text-zinc-300 overflow-x-auto whitespace-pre-wrap break-words",
  /* Icon sizes */
  iconSm: "w-3 h-3",
  iconMd: "w-4 h-4",
  iconLg: "w-12 h-12",
  icon6: "w-6 h-6",

  /* Home page */
  homeRoot: "flex flex-col min-h-[75vh] justify-between",
  homeHero: "py-20 text-center",
  homeTitle: "text-5xl font-extrabold text-zinc-800 dark:text-zinc-100 mb-6 tracking-tight",
  homeSubtitle: "text-lg text-zinc-600 dark:text-zinc-400",
  homePinnedHeading: "text-sm font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-500 mb-4 px-1",
  homeGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6",

  /* Projects - entry */
  projectMetaRow: "flex justify-between items-center py-1 border-b border-zinc-100 dark:border-zinc-800/50 last:border-0 flex-wrap gap-x-2",
  projectMetaLabel: "text-zinc-500 dark:text-zinc-400 text-[10px] uppercase font-bold tracking-wide",
  projectMetaValue: "text-zinc-800 dark:text-zinc-200 text-sm",
  projectMetaBox: "bg-white dark:bg-[#18181b] p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 shadow-sm text-sm",
  projectMetaHeading: "font-bold text-[10px] text-zinc-500 uppercase mb-2 tracking-wider",
  projectLinksContainer: "mt-3 pt-2 border-t border-zinc-200 dark:border-zinc-800",
  projectLinkButton: "flex items-center justify-between px-2.5 py-1.5 bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-200 dark:border-zinc-700/50 rounded hover:bg-zinc-100 dark:hover:bg-zinc-800 hover:border-blue-400 dark:hover:border-blue-500 hover:text-blue-600 dark:hover:text-blue-400 transition-all group text-xs",
  projectLinkText: "font-medium capitalize text-zinc-700 dark:text-zinc-300 text-sm group-hover:text-blue-600 dark:group-hover:text-blue-400",

  /* Projects - page */
  projectsRoot: "",
  projectsAdvancedBox: "mb-6 bg-white dark:bg-[#121214] border border-zinc-200 dark:border-zinc-800 rounded-lg p-4 shadow-sm animate-fadeIn",
  projectsSearchRow: "flex flex-col gap-4",
  projectsSearchInputWrapper: "flex items-center bg-zinc-100 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700 rounded-lg px-4 py-2 focus-within:ring-2 ring-blue-500/50",
  projectsSearchIcon: "w-5 h-5 text-zinc-500 mr-3 shrink-0",
  projectsSearchInput: "w-full bg-transparent text-sm text-zinc-800 dark:text-zinc-200 focus:outline-none placeholder-zinc-500",
  projectsSearchHelperBox: "mt-2 p-3 bg-zinc-50 dark:bg-zinc-900 rounded border border-zinc-200 dark:border-zinc-800 grid grid-cols-1 md:grid-cols-2 gap-2",
  projectsFiltersHeader: "flex justify-between items-center border-b border-zinc-100 dark:border-zinc-800 pb-2",
  projectsFiltersTitle: "text-xs font-bold uppercase text-zinc-400",
  projectsResetBtn: "text-xs text-blue-600 dark:text-blue-400 hover:underline",
  projectsToggleRow: "flex items-center gap-4 flex-wrap",
  projectsControlRow: "flex items-center gap-2",
  projectsToggleBtn: "flex items-center gap-1 text-sm font-medium px-2 py-1 rounded transition-colors",
  projectsLayoutToggleWrapper: "relative bg-zinc-200 dark:bg-zinc-800 p-1 rounded-lg flex shrink-0 ml-auto",
  projectsLayoutToggleHandle: "absolute top-1 bottom-1 w-8 bg-white dark:bg-zinc-600 rounded shadow-sm transition-all duration-300 ease-in-out",
  projectsLayoutIconBtn: "relative z-10 p-1.5 text-zinc-500 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors",
  projectsGridContainer: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6 pb-20",
  projectsListWrapper: "w-full text-sm text-zinc-800 dark:text-zinc-200 pb-20 overflow-x-auto",
  projectsListInner: "min-w-[1000px]",
  projectsListRow: `${""}${""}`,
  projectsListCellDesc: "text-left",
  projectsListTagsWrapper: "flex items-center gap-2 overflow-hidden h-full text-left flex-nowrap",
  projectsListTagInner: "flex items-center gap-2",
  projectsListTextXs: "text-zinc-500 dark:text-zinc-400 text-xs truncate text-left",
  projectsListMono: "text-zinc-500 dark:text-zinc-400 text-xs truncate text-left font-mono",

  /* Search results */
  searchRootContainer: "max-w-4xl mx-auto py-8",
  searchHeaderBox: "mb-10 border-b border-zinc-200 dark:border-zinc-800 pb-6",
  searchTitle: "text-3xl font-extrabold text-zinc-900 dark:text-zinc-100 tracking-tight",
  searchSubtitle: "text-sm text-zinc-500 dark:text-zinc-400 mt-2",
  searchNoResultsBox: "py-20 text-center bg-zinc-50 dark:bg-zinc-900/50 rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800",
  searchGrid: "grid gap-4 animate-fadeIn",
  searchResultCard: "group relative block bg-white dark:bg-[#18181b] border border-zinc-200 dark:border-zinc-800 rounded-xl p-6 transition-all duration-200 hover:shadow-lg hover:border-blue-400/50 dark:hover:border-blue-500/30 hover:-translate-y-0.5",
  searchResultIconLarge: "absolute top-6 right-6 text-zinc-200 dark:text-zinc-800 group-hover:text-blue-100 dark:group-hover:text-blue-900/20",
  searchResultTitle: "text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-2",

  /* Photography */
  photoGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 animate-fadeIn",
  photoTile: "group aspect-square bg-zinc-200 dark:bg-zinc-800 rounded-lg flex items-center justify-center relative overflow-hidden cursor-pointer",
  photoImg: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-105",
  photoOverlay: "absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300",
  photoCaptionBox: "absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300",
  photoCaptionText: "text-white text-sm font-bold truncate",
  photoMoreText: "text-sm text-zinc-500 italic",
  photoMoreWrapper: "mt-12 text-center",
  photoModalBackdrop: "fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 md:p-8 animate-fadeIn",
  photoModalInnerBase: "relative bg-white dark:bg-[#18181b] rounded-xl shadow-2xl w-full max-w-7xl overflow-hidden flex transition-all duration-300",
  photoModalSideView: "flex-col lg:flex-row h-[85vh]",
  photoModalDefaultView: "flex-col h-[85vh]",
  photoModalImageWrapperBase: "relative bg-zinc-100 dark:bg-[#09090b] flex items-center justify-center p-2 group/image",
  photoModalImageFitMax: "max-w-full object-contain shadow-sm w-full h-full",
  photoModalNavBtn: "absolute left-4 p-3 rounded-full bg-black/20 hover:bg-black/40 text-white backdrop-blur-md transition-all border border-white/10 z-20",
  photoModalNavDisabled: "opacity-50 cursor-not-allowed hover:bg-black/20",
  photoModalNavEnabled: "opacity-100",
  photoModalCloseBtn: "p-2 text-zinc-400 hover:text-zinc-800 dark:hover:text-zinc-200 transition-colors",
  photoModalDetails: "p-8",
  photoDetailTitle: "text-2xl font-bold text-zinc-900 dark:text-zinc-100 mb-6",
  photoDetailDesc: "text-zinc-600 dark:text-zinc-300 leading-relaxed font-light",
  photoMetaRow: "mt-8 pt-8 border-t border-zinc-100 dark:border-zinc-800 flex flex-col gap-3",
  photoMetaItemRow: "flex justify-between text-xs text-zinc-400 dark:text-zinc-500 uppercase tracking-wider font-bold",
  photoMetaMono: "font-mono text-zinc-600 dark:text-zinc-300 text-right",
  projectGridCard: "group flex flex-col bg-zinc-200 dark:bg-[#18181b] rounded-lg overflow-hidden border border-transparent hover:border-zinc-300 dark:hover:border-zinc-600 hover:shadow-lg hover:-translate-y-1 transition-all duration-200 h-64",
  projectGridCardTop: "p-[7px] bg-zinc-200 dark:bg-[#18181b] transition-colors duration-200",
  projectGridImageWrapper: "h-32 w-full bg-zinc-100 dark:bg-[#202024] rounded-sm flex items-center justify-center text-zinc-300 dark:text-zinc-600 group-hover:text-zinc-400 dark:group-hover:text-zinc-500 transition-colors",
  projectCardBody: "px-4 pb-4 pt-0 flex flex-col flex-1 justify-between overflow-hidden",
  projectTitle: "text-sm font-bold text-zinc-800 dark:text-zinc-100 truncate",
  projectDesc: "text-xs text-zinc-500 dark:text-zinc-400 mt-1 line-clamp-2 leading-relaxed",
  projectTagsRow: "flex items-center gap-1 mt-2 flex-nowrap overflow-hidden h-6",
  tagInline: "inline-block px-2 py-0.5 text-[10px] font-bold rounded shrink-0",

  navbarRoot: "w-full bg-zinc-50 dark:bg-[#09090b] border-b border-zinc-200 dark:border-zinc-800 transition-colors duration-200 sticky top-0 z-50",
  navbarInner: "mx-[10%] lg:mx-[18%] h-16 flex items-center justify-between relative bg-zinc-50 dark:bg-[#09090b] transition-colors duration-200 z-20",
  navbarLeft: "flex items-center gap-4 shrink-0 z-30",
  navMenuButton: "p-2 text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors lg:hidden -ml-2 rounded-full",
  navBrand: "text-xl font-bold text-zinc-800 dark:text-zinc-100 tracking-tight",
  navHiddenLinks: "hidden lg:flex items-center",
  navDivider: "h-6 w-px bg-zinc-300 dark:bg-zinc-700 mx-6",
  navLinksList: "flex gap-6 text-sm font-medium text-zinc-600 dark:text-zinc-400",
  navLinkItem: "hover:text-black dark:hover:text-white transition",
  navSearchDesktopWrapper: "hidden 2xl:flex flex-1 justify-start px-4 pl-8",
  navSearchBox: "flex w-full max-w-2xl items-center",
  navSearchInputContainer: "flex flex-1 items-center bg-white dark:bg-[#121214] border border-zinc-300 dark:border-zinc-700 rounded-l-full px-4 py-1.5 shadow-sm focus-within:border-blue-500 overflow-hidden transition-colors duration-200",
  navSearchInput: "w-full bg-transparent text-sm text-zinc-800 dark:text-zinc-200 focus:outline-none placeholder-zinc-500",
  navSearchButton: "px-5 py-1.5 bg-zinc-100 dark:bg-zinc-800 border border-l-0 border-zinc-300 dark:border-zinc-700 rounded-r-full hover:bg-zinc-200 dark:hover:bg-zinc-700 text-zinc-600 dark:text-zinc-400 transition-colors duration-200",
  navIconButton: "p-2 text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors",
  navMobileSearchToggle: "2xl:hidden p-2 text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors",
  mobileSearchContainer: "2xl:hidden border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090b] px-4 py-3",
  mobileMenuContainer: "lg:hidden border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090b]",
  mobileMenuList: "flex flex-col p-4 gap-4 text-sm font-medium text-zinc-600 dark:text-zinc-400",
};

export const ALL_CLASSNAMES = [
  "2xl:hidden border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090b] px-4 py-3",
  "absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300",
  "absolute bottom-4 left-4 p-2 rounded-lg bg-black/30 hover:bg-black/50 text-white/80 hover:text-white backdrop-blur-md transition-all border border-white/10 text-xs font-bold uppercase tracking-wider z-20 flex items-center gap-2",
  "absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300",
  "absolute left-2 top-1.5 text-xs text-zinc-400",
  "absolute top-0 left-0 right-0 h-32 bg-gradient-to-b from-black/60 to-transparent opacity-0 group-hover/topzone:opacity-100 transition-opacity duration-300 pointer-events-none",
  "absolute top-0 left-0 right-0 h-48 z-10 group/topzone pointer-events-auto",
  "absolute top-4 right-4 p-2 text-white hover:text-white/80 transition-colors bg-black/20 hover:bg-black/40 rounded-full backdrop-blur-sm pointer-events-auto",
  "absolute top-6 right-6 text-zinc-200 dark:text-zinc-800 group-hover:text-blue-100 dark:group-hover:text-blue-900/20 transition-colors",
  "absolute top-full left-0 mt-1 w-48 max-h-60 overflow-y-auto bg-white dark:bg-[#18181b] border border-zinc-200 dark:border-zinc-700 rounded-lg shadow-xl z-20",
  "animate-fadeIn",
  "bg-white dark:bg-[#18181b] p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 shadow-sm text-sm",
  "bg-zinc-50 dark:bg-zinc-900 rounded-lg p-6 border border-zinc-200 dark:border-zinc-800",
  "block lg:hidden mb-8 space-y-4",
  "block px-4 py-2 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded",
  "block w-fit",
  "border-zinc-200 dark:border-zinc-800",
  "col-span-1 md:col-span-2 text-zinc-400 italic mt-1",
  "fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 md:p-8 animate-fadeIn",
  "flex bg-zinc-100 dark:bg-zinc-800 rounded p-0.5",
  "flex flex-1 items-center bg-white dark:bg-[#121214] border border-zinc-300 dark:border-zinc-700 rounded-l-full px-4 py-1.5 shadow-sm focus-within:border-blue-500 overflow-hidden transition-colors duration-200",
  "flex flex-col",
  "flex flex-col gap-1.5",
  "flex flex-col gap-2 group",
  "flex flex-col gap-4",
  "flex flex-col lg:flex-row gap-8 lg:gap-12",
  "flex flex-col mb-6",
  "flex flex-col min-h-[75vh] justify-between",
  "flex flex-col min-h-screen bg-zinc-100 dark:bg-[#111114] text-zinc-900 dark:text-zinc-100 transition-colors duration-200 font-sans",
  "flex flex-col min-w-[1000px]",
  "flex flex-col p-4 gap-4 text-sm font-medium text-zinc-600 dark:text-zinc-400",
  "flex flex-wrap gap-2",
  "flex flex-wrap gap-2 max-h-32 overflow-y-auto pr-2 custom-scrollbar",
  "flex flex-wrap gap-4 text-sm text-zinc-500 dark:text-zinc-400",
  "flex gap-1",
  "flex gap-2 mb-10 overflow-x-auto pb-2 custom-scrollbar",
  "flex gap-6 text-sm font-medium text-zinc-600 dark:text-zinc-400",
  "flex items-center bg-zinc-100 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700 rounded-lg px-4 py-2 focus-within:ring-2 ring-blue-500/50",
  "flex items-center gap-1 mt-2 flex-nowrap overflow-hidden h-6",
  "flex items-center gap-1 text-sm font-medium text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-800 px-2 py-1 rounded transition-colors whitespace-nowrap",
  "flex items-center gap-2",
  "flex items-center gap-2 animate-fadeIn ml-2",
  "flex items-center gap-2 overflow-hidden h-full text-left flex-nowrap",
  "flex items-center gap-2 shrink-0 z-30",
  "flex items-center gap-2 text-xs font-bold text-zinc-400 dark:text-zinc-500 mb-2 uppercase tracking-wider",
  "flex items-center gap-3",
  "flex items-center gap-3 text-sm text-zinc-500 dark:text-zinc-400 font-mono mb-6",
  "flex items-center gap-3 truncate font-medium text-zinc-700 dark:text-zinc-200 group-hover:text-blue-600 dark:group-hover:text-blue-400 text-left",
  "flex items-center gap-4 flex-wrap",
  "flex items-center gap-4 shrink-0 z-30",
  "flex items-center justify-between flex-wrap gap-4",
  "flex items-center justify-between px-2.5 py-1.5 bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-200 dark:border-zinc-700/50 rounded hover:bg-zinc-100 dark:hover:bg-zinc-800 hover:border-blue-400 dark:hover:border-blue-500 hover:text-blue-600 dark:hover:text-blue-400 transition-all group text-xs",
  "flex justify-between items-center border-b border-zinc-100 dark:border-zinc-800 pb-2",
  "flex justify-between items-center mb-2",
  "flex justify-between items-center p-3 bg-white dark:bg-zinc-800/50 rounded-lg border border-zinc-200 dark:border-zinc-700/50",
  "flex justify-between items-center py-1 border-b border-zinc-100 dark:border-zinc-800/50 last:border-0 flex-wrap gap-x-2",
  "flex justify-between text-xs text-zinc-400 dark:text-zinc-500 uppercase tracking-wider font-bold",
  "flex justify-end p-4 pb-0",
  "flex w-full items-center",
  "flex w-full max-w-2xl items-center",
  "flex-1 min-w-0",
  "font-bold text-[10px] text-zinc-500 uppercase mb-2 tracking-wider",
  "font-bold text-sm text-zinc-700 dark:text-zinc-200",
  "font-medium capitalize text-zinc-700 dark:text-zinc-300 text-sm group-hover:text-blue-600 dark:group-hover:text-blue-400",
  "font-mono bg-zinc-200 dark:bg-zinc-800 px-1 rounded",
  "font-mono font-bold text-blue-600 dark:text-blue-400",
  "font-mono text-sm text-zinc-700 dark:text-zinc-300 overflow-x-auto whitespace-pre-wrap break-words",
  "font-mono text-zinc-600 dark:text-zinc-300 text-right",
  "grid gap-4 animate-fadeIn",
  "grid grid-cols-1 md:grid-cols-2 gap-8 mt-8",
  "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 animate-fadeIn",
  "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6",
  "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-6 pb-20",
  "grid grid-cols-2 gap-4",
  "group aspect-square bg-zinc-200 dark:bg-zinc-800 rounded-lg flex items-center justify-center relative overflow-hidden cursor-pointer",
  "group bg-white dark:bg-[#18181b] border border-zinc-200 dark:border-zinc-800 rounded-xl p-6 transition-all duration-200 hover:shadow-lg hover:border-blue-400/50 dark:hover:border-blue-500/30 hover:-translate-y-0.5",
  "group flex flex-col bg-zinc-200 dark:bg-[#18181b] rounded-lg overflow-hidden border border-transparent hover:border-zinc-300 dark:hover:border-zinc-600 hover:shadow-lg hover:-translate-y-1 transition-all duration-200 h-64",
  "group relative block bg-white dark:bg-[#18181b] border border-zinc-200 dark:border-zinc-800 rounded-xl p-6 transition-all duration-200 hover:shadow-lg hover:border-blue-400/50 dark:hover:border-blue-500/30 hover:-translate-y-0.5",
  "h-32 w-full bg-zinc-100 dark:bg-[#202024] rounded-sm flex items-center justify-center text-zinc-300 dark:text-zinc-600 group-hover:text-zinc-400 dark:group-hover:text-zinc-500 transition-colors",
  "h-6 w-px bg-zinc-300 dark:bg-zinc-700 mx-6",
  "hidden 2xl:flex flex-1 justify-start px-4 pl-8",
  "hidden lg:block w-64 shrink-0",
  "hidden lg:flex items-center",
  "hover:text-black dark:hover:text-white transition",
  "hover:text-blue-500 transition-colors",
  "italic text-zinc-500",
  "lg:hidden border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#09090b]",
  "max-w-3xl mx-auto py-8 animate-fadeIn",
  "max-w-4xl mx-auto py-8",
  "max-w-full",
  "max-w-full mx-auto py-8 animate-fadeIn",
  "max-w-sm",
  "mb-10 border-b border-zinc-200 dark:border-zinc-800 pb-6",
  "mb-6 bg-white dark:bg-[#121214] border border-zinc-200 dark:border-zinc-800 rounded-lg p-4 shadow-sm animate-fadeIn",
  "mb-8",
  "mb-8 border-b border-zinc-200 dark:border-zinc-800 pb-6",
  "mt-12 p-8 bg-zinc-100 dark:bg-zinc-900 rounded-lg text-center text-zinc-500",
  "mt-12 text-center",
  "mt-2 p-3 bg-zinc-50 dark:bg-zinc-900 rounded border border-zinc-200 dark:border-zinc-800 grid grid-cols-1 md:grid-cols-2 gap-2",
  "mt-2 text-blue-600 dark:text-blue-400 text-sm font-medium flex items-center gap-1 hover:gap-2 transition-all w-fit",
  "mt-3 pt-2 border-t border-zinc-200 dark:border-zinc-800",
  "mt-4",
  "mt-8 pt-8 border-t border-zinc-100 dark:border-zinc-800 flex flex-col gap-3",
  "mt-auto pt-12",
  "mx-[10%] lg:mx-[18%] h-16 flex items-center justify-between relative bg-zinc-50 dark:bg-[#09090b] transition-colors duration-200 z-20",
  "mx-[10%] lg:mx-[18%] py-8 flex-1",
  "my-6 rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#18181b]",
  "p-2 text-zinc-400 hover:text-zinc-800 dark:hover:text-zinc-200 transition-colors",
  "p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg text-center",
  "p-4 bg-violet-50 dark:bg-violet-900/20 rounded-lg text-center",
  "p-4 overflow-x-auto",
  "p-8 bg-zinc-50 dark:bg-zinc-900 rounded-lg text-center text-zinc-500",
  "p-[7px] bg-zinc-200 dark:bg-[#18181b] transition-colors duration-200",
  "prose dark:prose-invert max-w-none",
  "prose dark:prose-invert max-w-none text-zinc-700 dark:text-zinc-300",
  "px-4 pb-4 pt-0 flex flex-col flex-1 justify-between overflow-hidden",
  "px-4 py-2 bg-zinc-100 dark:bg-zinc-800/50 border-b border-zinc-200 dark:border-zinc-800 text-xs font-mono text-zinc-500 uppercase",
  "px-5 py-1.5 bg-zinc-100 dark:bg-zinc-800 border border-l-0 border-zinc-300 dark:border-zinc-700 rounded-r-full hover:bg-zinc-200 dark:hover:bg-zinc-700 text-zinc-600 dark:text-zinc-400 transition-colors duration-200",
  "py-20 text-center",
  "py-20 text-center bg-zinc-50 dark:bg-zinc-900/50 rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800",
  "relative",
  "relative bg-zinc-200 dark:bg-zinc-800 p-1 rounded-lg flex shrink-0 ml-auto",
  "relative z-10",
  "relative z-10 p-1.5 text-zinc-500 dark:text-zinc-400 hover:text-black dark:hover:text-white transition-colors",
  "shrink-0",
  "space-y-1",
  "space-y-12 animate-fadeIn",
  "space-y-4",
  "sticky top-24 space-y-6",
  "text-2xl font-bold text-blue-600 dark:text-blue-400",
  "text-2xl font-bold text-violet-600 dark:text-violet-400",
  "text-2xl font-bold text-zinc-800 dark:text-zinc-100 hover:text-blue-600 dark:hover:text-blue-400 transition-colors",
  "text-2xl font-bold text-zinc-900 dark:text-zinc-100 mb-6",
  "text-3xl font-extrabold text-zinc-900 dark:text-zinc-100 tracking-tight",
  "text-5xl font-extrabold text-zinc-800 dark:text-zinc-100 mb-6 tracking-tight",
  "text-5xl mb-4 opacity-50",
  "text-[10px] font-bold uppercase tracking-wider text-zinc-400 border border-zinc-200 dark:border-zinc-800 px-1.5 py-0.5 rounded",
  "text-center md:text-left",
  "text-center py-20 text-zinc-400 italic",
  "text-center py-20 text-zinc-500",
  "text-emerald-600 dark:text-emerald-400 font-medium bg-emerald-50 dark:bg-emerald-900/20 px-1.5 py-0.5 rounded text-[10px]",
  "text-left",
  "text-lg font-medium text-zinc-900 dark:text-zinc-100",
  "text-lg text-zinc-600 dark:text-zinc-400",
  "text-sm font-bold text-zinc-800 dark:text-zinc-100 truncate",
  "text-sm font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-500 mb-4 px-1",
  "text-sm font-mono text-green-600 dark:text-green-400",
  "text-sm font-mono text-zinc-700 dark:text-zinc-300",
  "text-sm text-zinc-500 dark:text-zinc-400 mt-2",
  "text-sm text-zinc-500 italic",
  "text-white text-sm font-bold truncate",
  "text-xl font-bold text-zinc-800 dark:text-zinc-100 tracking-tight",
  "text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-2",
  "text-xl font-bold text-zinc-900 dark:text-zinc-100 mb-2 group-hover:text-blue-600 dark:group-hover:text-blue-400",
  "text-xs bg-transparent border border-zinc-300 dark:border-zinc-600 rounded px-2 py-1 dark:text-white dark:[color-scheme:dark]",
  "text-xs font-bold uppercase text-zinc-400",
  "text-xs font-bold uppercase text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors mb-4 inline-flex items-center gap-1",
  "text-xs font-bold uppercase text-zinc-400 mb-2 tracking-wider px-1",
  "text-xs font-bold uppercase text-zinc-400 mb-3 tracking-wider px-1",
  "text-xs font-bold uppercase text-zinc-500",
  "text-xs font-bold uppercase text-zinc-500 mb-2",
  "text-xs font-mono text-zinc-400 dark:text-zinc-500",
  "text-xs text-blue-600 dark:text-blue-400 hover:underline",
  "text-xs text-blue-800 dark:text-blue-300 uppercase tracking-wide font-bold mt-1",
  "text-xs text-violet-800 dark:text-violet-300 uppercase tracking-wide font-bold mt-1",
  "text-xs text-zinc-500",
  "text-xs text-zinc-500 cursor-pointer select-none",
  "text-xs text-zinc-500 dark:text-zinc-400 mt-1 line-clamp-2 leading-relaxed",
  "text-zinc-300 dark:text-zinc-600",
  "text-zinc-400",
  "text-zinc-500 dark:text-zinc-400 text-[10px] uppercase font-bold tracking-wide",
  "text-zinc-500 dark:text-zinc-400 text-xs truncate text-left",
  "text-zinc-500 dark:text-zinc-400 text-xs truncate text-left font-mono",
  "text-zinc-500 dark:text-zinc-400 truncate text-left",
  "text-zinc-500 dark:text-zinc-500",
  "text-zinc-500 mt-1",
  "text-zinc-600 dark:text-zinc-300 leading-relaxed font-light",
  "text-zinc-800 dark:text-zinc-200",
  "text-zinc-800 dark:text-zinc-200 font-medium italic",
  "truncate",
  "uppercase tracking-wider font-sans font-bold text-[10px] bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded",
  "w-10 h-10",
  "w-12 h-12",
  "w-20 pl-8 bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded px-2 py-1 text-sm text-zinc-700 dark:text-zinc-200 focus:border-blue-500 focus:outline-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
  "w-3 h-3",
  "w-3 h-3 text-zinc-400 group-hover:text-blue-500",
  "w-4 h-4",
  "w-4 h-4 text-zinc-400 mr-2 shrink-0",
  "w-5 h-5",
  "w-5 h-5 text-zinc-500 mr-3 shrink-0",
  "w-6 h-6",
  "w-full bg-transparent text-sm text-zinc-800 dark:text-zinc-200 focus:outline-none placeholder-zinc-500",
  "w-full bg-zinc-50 dark:bg-[#09090b] border-b border-zinc-200 dark:border-zinc-800 transition-colors duration-200 sticky top-0 z-50",
  "w-full h-full object-cover transition-transform duration-500 group-hover:scale-105",
  "w-full py-6 text-center text-xs text-zinc-400 dark:text-zinc-600 bg-transparent",
  "w-full text-left px-4 py-2 text-sm text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-700",
  "w-full text-sm text-zinc-800 dark:text-zinc-200 pb-20 overflow-x-auto"
];
